### ISSUE TITLE
네비게이션 이슈

### ISSUE THREAD

**Issue by koreakane** [gamramstone-dev/gamramstone-issues#12]
- [x] 채널별 진행 상황에서 진행률 등을 눌러 영상을 확인한 후에 뒤로 가기를 하면 채널별 진행 상황이 아니라 영상 탭으로 계속 이동이 됨
- [ ] 페이지를 누르고 옛날 영상을 누른 뒤에 뒤로가기를 하면 1번 페이지로 이동이 되어버림

**Comment by koreakane** [comment]
![Uploading code.png…]()

**Comment by koreakane** [comment]
`pages/videos.tsx` 코드의 696번줄 router.replace가 첫 번째 이슈를 일으켰던 것 같습니다. 일단 주석 처리했고, 콘솔을 찍어보니까 같은 string인데 다른 string으로 인식해 해당 버그가 일어나더라고요. 해당 코드가 어떤 역할을 하는 지 잘 모르겠는데 알려주신다면 감사합니다.

![code](https://user-images.githubusercontent.com/38726323/211144778-6ed232c6-55b9-45c5-ad2f-5ef163828e68.png)

**Comment by So-chiru** [comment]
params가 바뀌면 페이지 URL을 업데이트하는 코드인데 이거 삭제하면 현재 사이트 동작처럼 페이지 URL이 반영이 안됩니다

router.replace말고 다른 방법을 찾아봐야겠네요

**Comment by koreakane** [comment]
그럼 롤백하고 다시 찾아보겠습니다

**Comment by So-chiru** [comment]
지금 videos 페이지 쿼리 처리하는 로직이 깔끔하지 않아서 이 문제 해결한다고 코드 몇가지 추가하는 것보다는 페이지 코드 새로 짜는게 나아보여서 이 이슈는 미뤄두면 좋을 것 같습니다 🙏

**Comment by So-chiru** [comment]
#13

**Comment by So-chiru** [comment]
queries, 라우터에서 제공하는 쿼리 두 가지 상태로 나눠서 관리하다 보니 이슈가 많아서 깔끔하게 라우터 쿼리만 사용하도록 해서 해결했습니다!
