### ISSUE TITLE
멘션 버그

### ISSUE THREAD

**Issue by koreakane** [gamramstone-dev/gamramstone-issues#15]
토론이나 댓글에 @멘션을 하는 경우 처음에는 잘 되는데 수정을 하면 @<id>로 뜨면서 다시 멘션이 안됨

**Comment by koreakane** [comment]
@So-chiru 이 이슈 진행중인데 assign이 안되네요 public이라 안되는건가요?

**Comment by koreakane** [comment]
@So-chiru 

수정 시 `v1/discussion/${id}` API로 PUT 메소드를 보내는데 POST로 받은 댓글 정보랑 title 필드 하나 차이나는것 말고는 내용은 같은데 백단에서 다시 comments로 받아오는 데이터에서는 멘션 스트링 파싱이 제대로 안 되서 옵니다. PUT으로 보내는 데이터 로직 체크 한번 부탁드립니다.
그리고 이렇게 스트링 파싱이 깨지면 수정에서 해당 유저에게 멘션도 제대로 안 가는 것 같습니다.

<img width="431" alt="스크린샷 2023-01-07 오후 5 06 02" src="https://user-images.githubusercontent.com/38726323/211140670-069e4ff2-d187-49ad-bc2e-7be5af3736ab.png">

<img width="431" alt="스크린샷 2023-01-07 오후 5 05 48" src="https://user-images.githubusercontent.com/38726323/211140663-7917c524-7a13-4e3f-a13b-9f8a329f86a5.png">

이와는 별개로 아래처럼 수정 시 멘션 된 부분은 멘션이 풀리게 되고 멘션 문법으로만 나타나게 되는데, 이 부분은 피드백이 없어서 그대로 둘려고 합니다. 멘션 노드로 변환시키면 수정 시 의도치 않은 재 멘션을 할 것 같아서 위 버그만 수정되면 괜찮을 것 같습니다.

<img width="613" alt="스크린샷 2023-01-07 오후 5 11 23" src="https://user-images.githubusercontent.com/38726323/211140818-5d8729eb-00d9-4f38-8451-771d5f42296f.png">

**Comment by So-chiru** [comment]
요거는 백엔드 이슈라 백엔드에서 처리하겠습니다

**Comment by So-chiru** [comment]
Tiptap 에디터로 교체하면서 아예 HTML으로 받아 span[data-type="mention"] 받는 식으로 해결했습니다
