### ISSUE TITLE
특수코드 변환 이슈

### ISSUE THREAD

**Issue by koreakane** [gamramstone-dev/gamramstone-issues#22]
사전 등 표시과정에서 &가 특수코드 &amp; 로 표시되는 현상이 있음

특정 특수 문자 & ' " > <등 이 제대로 표기 안되고 HTML코드로 인식되서 표기되는 중

![image](https://user-images.githubusercontent.com/38726323/211464192-f7447c03-005a-4bf2-b72e-8c2960dbe3c3.png)

**Comment by So-chiru** [comment]
프론트에서 해결 완료
