### ISSUE TITLE
업로드 사이트에서 중국어(대만)이 languages.zh-TW으로 표시되는 오류 

### ISSUE THREAD

**Issue by Trashnokdu** [gamramstone-dev/gamramstone-issues#24]
![image](https://user-images.githubusercontent.com/72365216/224489320-0f1f4d83-61a5-4285-928c-fed0d4c5804b.png)

아마 중국어를 나누시면서 structs/common.ts안에 ISO639와 LanguageNames 에 zh-TW넣으시는걸 까먹으신것 같습니다

**Comment by So-chiru** [comment]
현재 수정은 완료되었으나 아직 다른 부분 작업이 남아 있어서 배포까지 조금 걸릴 수 있습니다
