### ISSUE TITLE
토론탭에서 사용자를 멘션할때 닉네임에 띄어쓰기가 있으면 멘션이 안되는것같습니다

### ISSUE THREAD

**Issue by Trashnokdu** [gamramstone-dev/gamramstone-issues#25]
일반닉을 멘션할때는 아무런 문제가 없지만 닉에 띄어쓰기가 들어가있으면 하이라이트가 안됩니다

**Comment by So-chiru** [comment]
에디터 교체 후 증상은 여전하지만 이전과 같이 태그를 걸 때 이슈가 크게 발생하지는 않아서 무기한 보류하겠습니다.
