### ISSUE TITLE
비챤님이 사이트에서 자동연동이 안된다고 하십니다

### ISSUE THREAD

**Issue by Trashnokdu** [gamramstone-dev/gamramstone-issues#6]
클립 : https://clips.twitch.tv/ScarySourTriangleCoolStoryBro-0XMRXeM1cBzrVFby

**Comment by So-chiru** [comment]
우선 권한 드리는 방식으로 비챤님 로그인 문제 해결은 했는데
추후에 https://github.com/gamramstone-dev/gamramstone/issues/13 작업하면서 한꺼번에 처리해야 할 것 같습니다
